// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: global_planner_config.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "global_planner_config.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace rrts {
namespace planning {
namespace global_planner {

namespace {

const ::google::protobuf::Descriptor* GlobalPlannerConfig_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GlobalPlannerConfig_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_global_5fplanner_5fconfig_2eproto() {
  protobuf_AddDesc_global_5fplanner_5fconfig_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "global_planner_config.proto");
  GOOGLE_CHECK(file != NULL);
  GlobalPlannerConfig_descriptor_ = file->message_type(0);
  static const int GlobalPlannerConfig_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GlobalPlannerConfig, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GlobalPlannerConfig, selected_algorithm_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GlobalPlannerConfig, frequency_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GlobalPlannerConfig, max_retries_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GlobalPlannerConfig, goal_distance_tolerance_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GlobalPlannerConfig, goal_angle_tolerance_),
  };
  GlobalPlannerConfig_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      GlobalPlannerConfig_descriptor_,
      GlobalPlannerConfig::default_instance_,
      GlobalPlannerConfig_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GlobalPlannerConfig, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GlobalPlannerConfig, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(GlobalPlannerConfig));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_global_5fplanner_5fconfig_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    GlobalPlannerConfig_descriptor_, &GlobalPlannerConfig::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_global_5fplanner_5fconfig_2eproto() {
  delete GlobalPlannerConfig::default_instance_;
  delete GlobalPlannerConfig_reflection_;
}

void protobuf_AddDesc_global_5fplanner_5fconfig_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\033global_planner_config.proto\022\034rrts.plan"
    "ning.global_planner\"\246\001\n\023GlobalPlannerCon"
    "fig\022\014\n\004name\030\001 \003(\t\022\032\n\022selected_algorithm\030"
    "\002 \001(\t\022\021\n\tfrequency\030\003 \002(\005\022\023\n\013max_retries\030"
    "\004 \002(\005\022\037\n\027goal_distance_tolerance\030\005 \002(\001\022\034"
    "\n\024goal_angle_tolerance\030\006 \002(\001", 228);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "global_planner_config.proto", &protobuf_RegisterTypes);
  GlobalPlannerConfig::default_instance_ = new GlobalPlannerConfig();
  GlobalPlannerConfig::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_global_5fplanner_5fconfig_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_global_5fplanner_5fconfig_2eproto {
  StaticDescriptorInitializer_global_5fplanner_5fconfig_2eproto() {
    protobuf_AddDesc_global_5fplanner_5fconfig_2eproto();
  }
} static_descriptor_initializer_global_5fplanner_5fconfig_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int GlobalPlannerConfig::kNameFieldNumber;
const int GlobalPlannerConfig::kSelectedAlgorithmFieldNumber;
const int GlobalPlannerConfig::kFrequencyFieldNumber;
const int GlobalPlannerConfig::kMaxRetriesFieldNumber;
const int GlobalPlannerConfig::kGoalDistanceToleranceFieldNumber;
const int GlobalPlannerConfig::kGoalAngleToleranceFieldNumber;
#endif  // !_MSC_VER

GlobalPlannerConfig::GlobalPlannerConfig()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:rrts.planning.global_planner.GlobalPlannerConfig)
}

void GlobalPlannerConfig::InitAsDefaultInstance() {
}

GlobalPlannerConfig::GlobalPlannerConfig(const GlobalPlannerConfig& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:rrts.planning.global_planner.GlobalPlannerConfig)
}

void GlobalPlannerConfig::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  selected_algorithm_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  frequency_ = 0;
  max_retries_ = 0;
  goal_distance_tolerance_ = 0;
  goal_angle_tolerance_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

GlobalPlannerConfig::~GlobalPlannerConfig() {
  // @@protoc_insertion_point(destructor:rrts.planning.global_planner.GlobalPlannerConfig)
  SharedDtor();
}

void GlobalPlannerConfig::SharedDtor() {
  if (selected_algorithm_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete selected_algorithm_;
  }
  if (this != default_instance_) {
  }
}

void GlobalPlannerConfig::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GlobalPlannerConfig::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GlobalPlannerConfig_descriptor_;
}

const GlobalPlannerConfig& GlobalPlannerConfig::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_global_5fplanner_5fconfig_2eproto();
  return *default_instance_;
}

GlobalPlannerConfig* GlobalPlannerConfig::default_instance_ = NULL;

GlobalPlannerConfig* GlobalPlannerConfig::New() const {
  return new GlobalPlannerConfig;
}

void GlobalPlannerConfig::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<GlobalPlannerConfig*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 62) {
    ZR_(frequency_, goal_angle_tolerance_);
    if (has_selected_algorithm()) {
      if (selected_algorithm_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        selected_algorithm_->clear();
      }
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  name_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool GlobalPlannerConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:rrts.planning.global_planner.GlobalPlannerConfig)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated string name = 1;
      case 1: {
        if (tag == 10) {
         parse_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name(this->name_size() - 1).data(),
            this->name(this->name_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_name;
        if (input->ExpectTag(18)) goto parse_selected_algorithm;
        break;
      }

      // optional string selected_algorithm = 2;
      case 2: {
        if (tag == 18) {
         parse_selected_algorithm:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_selected_algorithm()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->selected_algorithm().data(), this->selected_algorithm().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "selected_algorithm");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_frequency;
        break;
      }

      // required int32 frequency = 3;
      case 3: {
        if (tag == 24) {
         parse_frequency:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &frequency_)));
          set_has_frequency();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_max_retries;
        break;
      }

      // required int32 max_retries = 4;
      case 4: {
        if (tag == 32) {
         parse_max_retries:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &max_retries_)));
          set_has_max_retries();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(41)) goto parse_goal_distance_tolerance;
        break;
      }

      // required double goal_distance_tolerance = 5;
      case 5: {
        if (tag == 41) {
         parse_goal_distance_tolerance:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &goal_distance_tolerance_)));
          set_has_goal_distance_tolerance();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(49)) goto parse_goal_angle_tolerance;
        break;
      }

      // required double goal_angle_tolerance = 6;
      case 6: {
        if (tag == 49) {
         parse_goal_angle_tolerance:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &goal_angle_tolerance_)));
          set_has_goal_angle_tolerance();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:rrts.planning.global_planner.GlobalPlannerConfig)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:rrts.planning.global_planner.GlobalPlannerConfig)
  return false;
#undef DO_
}

void GlobalPlannerConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:rrts.planning.global_planner.GlobalPlannerConfig)
  // repeated string name = 1;
  for (int i = 0; i < this->name_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
    this->name(i).data(), this->name(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE,
    "name");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->name(i), output);
  }

  // optional string selected_algorithm = 2;
  if (has_selected_algorithm()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->selected_algorithm().data(), this->selected_algorithm().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "selected_algorithm");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->selected_algorithm(), output);
  }

  // required int32 frequency = 3;
  if (has_frequency()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->frequency(), output);
  }

  // required int32 max_retries = 4;
  if (has_max_retries()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->max_retries(), output);
  }

  // required double goal_distance_tolerance = 5;
  if (has_goal_distance_tolerance()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(5, this->goal_distance_tolerance(), output);
  }

  // required double goal_angle_tolerance = 6;
  if (has_goal_angle_tolerance()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(6, this->goal_angle_tolerance(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:rrts.planning.global_planner.GlobalPlannerConfig)
}

::google::protobuf::uint8* GlobalPlannerConfig::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:rrts.planning.global_planner.GlobalPlannerConfig)
  // repeated string name = 1;
  for (int i = 0; i < this->name_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name(i).data(), this->name(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "name");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(1, this->name(i), target);
  }

  // optional string selected_algorithm = 2;
  if (has_selected_algorithm()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->selected_algorithm().data(), this->selected_algorithm().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "selected_algorithm");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->selected_algorithm(), target);
  }

  // required int32 frequency = 3;
  if (has_frequency()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->frequency(), target);
  }

  // required int32 max_retries = 4;
  if (has_max_retries()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->max_retries(), target);
  }

  // required double goal_distance_tolerance = 5;
  if (has_goal_distance_tolerance()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(5, this->goal_distance_tolerance(), target);
  }

  // required double goal_angle_tolerance = 6;
  if (has_goal_angle_tolerance()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(6, this->goal_angle_tolerance(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rrts.planning.global_planner.GlobalPlannerConfig)
  return target;
}

int GlobalPlannerConfig::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[1 / 32] & (0xffu << (1 % 32))) {
    // optional string selected_algorithm = 2;
    if (has_selected_algorithm()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->selected_algorithm());
    }

    // required int32 frequency = 3;
    if (has_frequency()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->frequency());
    }

    // required int32 max_retries = 4;
    if (has_max_retries()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->max_retries());
    }

    // required double goal_distance_tolerance = 5;
    if (has_goal_distance_tolerance()) {
      total_size += 1 + 8;
    }

    // required double goal_angle_tolerance = 6;
    if (has_goal_angle_tolerance()) {
      total_size += 1 + 8;
    }

  }
  // repeated string name = 1;
  total_size += 1 * this->name_size();
  for (int i = 0; i < this->name_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->name(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GlobalPlannerConfig::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const GlobalPlannerConfig* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const GlobalPlannerConfig*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void GlobalPlannerConfig::MergeFrom(const GlobalPlannerConfig& from) {
  GOOGLE_CHECK_NE(&from, this);
  name_.MergeFrom(from.name_);
  if (from._has_bits_[1 / 32] & (0xffu << (1 % 32))) {
    if (from.has_selected_algorithm()) {
      set_selected_algorithm(from.selected_algorithm());
    }
    if (from.has_frequency()) {
      set_frequency(from.frequency());
    }
    if (from.has_max_retries()) {
      set_max_retries(from.max_retries());
    }
    if (from.has_goal_distance_tolerance()) {
      set_goal_distance_tolerance(from.goal_distance_tolerance());
    }
    if (from.has_goal_angle_tolerance()) {
      set_goal_angle_tolerance(from.goal_angle_tolerance());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void GlobalPlannerConfig::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GlobalPlannerConfig::CopyFrom(const GlobalPlannerConfig& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GlobalPlannerConfig::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000003c) != 0x0000003c) return false;

  return true;
}

void GlobalPlannerConfig::Swap(GlobalPlannerConfig* other) {
  if (other != this) {
    name_.Swap(&other->name_);
    std::swap(selected_algorithm_, other->selected_algorithm_);
    std::swap(frequency_, other->frequency_);
    std::swap(max_retries_, other->max_retries_);
    std::swap(goal_distance_tolerance_, other->goal_distance_tolerance_);
    std::swap(goal_angle_tolerance_, other->goal_angle_tolerance_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata GlobalPlannerConfig::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = GlobalPlannerConfig_descriptor_;
  metadata.reflection = GlobalPlannerConfig_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace global_planner
}  // namespace planning
}  // namespace rrts

// @@protoc_insertion_point(global_scope)
